80 mute unmute
bennyboer/bbb_app pull request #113
Opened 2020-12-01 19:51 UTC by bennyboer

Closes #80

2020-12-01 19:55 UTC, jo-code submitted a review, later dismissed
werd scho passn :D

2020-12-01 19:56 UTC, Gleydar submitted a review, later dismissed
I like my changes

2020-12-01 21:12 UTC, jo-code requested changes

2020-12-01 21:12 UTC, jo-code commented on lib/src/connect/meeting/main_websocket/main_websocket.dart
> +      } on FormatException catch (e) {
Please use logger

2020-12-03 09:49 UTC, jo-code approved these changes

2020-12-03 09:49 UTC, merged